version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - LANG=C.UTF-8
      - EDITOR=vim
    ports:
      - "${EXTERNAL_NODE_PORT:-3000}:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    tmpfs:
      - /tmp

volumes:
  node_modules:

